spring:
 cloud:
   gateway:
     routes:
       - id: reservation-microservice
         uri: http://localhost:8083/
         predicates:
           - Path=/reservation/**


       - id: hebergement-microservice
         uri: http://localhost:8082/
         predicates:
           - Path=/hebergement/**

       - id: reclamation-microservice
         uri: http://localhost:8084/
         predicates:
           - Path=/reclamations/**

       - id: user-microservice
         uri: http://localhost:8087/
         predicates:
           - Path=/users/**
       - id: reponse-microservice
         uri: http://localhost:8086/
         predicates:
           - Path=/reponse/**










 application:
   name: SWIGGY-GATEWAY

 security:
   oauth2:
     resourceserver:
       jwt:
         issuer-uri: http://localhost:9090/realms/SpringbootKeycloak

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/