spring:
 cloud:
   gateway:
     routes:



       - id: hebergement-microservice
         uri: http://localhost:8082/
         predicates:
           - Path=/hebergement/**

       - id: reclamation-microservice
         uri: http://localhost:8082/
         predicates:
           - Path=/reclamation/**








 application:
   name: SWIGGY-GATEWAY

 security:
   oauth2:
     resourceserver:
       jwt:
         issuer-uri: http://localhost:9090/realms/SpringbootKeycloak

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/